//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM_DEV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMONESTACIONES
    {
        public int ID_AMONESTACION { get; set; }
        public int ID_EMPLEADO { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_FINAL { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public string DESCRIPCION { get; set; }
        public string GOCE_SALARIO { get; set; }
        public string VERB_ESC { get; set; }
        public string AUTORIZACION { get; set; }
    
        public virtual EMPLEADOS EMPLEADOS { get; set; }
    }
}
