//------------------------------------------------------------------------------
// <auto-generated>
//     Este c贸digo se gener贸 a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicaci贸n.
//     Los cambios manuales en este archivo se sobrescribir谩n si se regenera el c贸digo.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM_DEV.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class AMONESTACIONES
    {
        public int ID_EMPRESA { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor, ingrese un nombre"), DisplayName("Nombre de la Empresa"), StringLength(45, ErrorMessage = "Longitud del nombre es muy extensa. Por favor no exceda los 45 caracteres."), RegularExpression("([A-Za-z])+( [A-Za-z_]+)*", ErrorMessage = "Formato Inv醠ido.")]
        public string NOMBRE { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor, ingrese la raz髇 social de la empresa"), DisplayName("Raz髇 Social"), StringLength(25, ErrorMessage = "Longitud de la raz髇 social es muy extensa. Por favor no exceda los 25 caracteres."), RegularExpression("([A-Za-z])+( [A-Za-z]+)*", ErrorMessage = "Formato Inv醠ido.")]
        public string RAZON_SOCIAL { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor, ingrese una c閐ula jur韉ica"), DisplayName("C閐ula Jur韉ica"), StringLength(25, ErrorMessage = "Longitud de la c閐ula jur韉ica es muy extensa. Por favor no exceda los 25 caracteres."), RegularExpression("^[0-9a-zA-Z;/?'*@-]*", ErrorMessage = "Formato Inv醠ido.")]
        public string CEDULA_JURIDICA { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor, ingrese la fecha de fundaci髇"), DisplayName("Fecha de Fundaci髇"), DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime FECHA_FUNDACION { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor, ingrese el pa韘 de or韌en"), DisplayName("Pa韘 de Or韌en"), StringLength(25, ErrorMessage = "El nombre del pa韘 de or韌en es muy extenso. Por favor no exceda los 25 caracteres."), RegularExpression("([A-Za-z])+( [A-Za-z]+)*", ErrorMessage = "Formato Inv醠ido.")]
        public string PAIS_ORIGEN { get; set; }




        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor, ingrese la sede central de la empresa"), DisplayName("Sede Central"), StringLength(25, ErrorMessage = "El nombre de la sede central es muy extenso. Por favor no exceda los 25 caracteres."), RegularExpression("([A-Za-z])+( [A-Za-z]+)*", ErrorMessage = "Formato Inv醠ido.")]
        public string SEDE_CENTRAL { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor, seleccione el estado de la empresa"), DisplayName("Estado")]
        public string ESTADO { get; set; }

    }
}
