//------------------------------------------------------------------------------
// <auto-generated>
//     Este c贸digo se gener贸 a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicaci贸n.
//     Los cambios manuales en este archivo se sobrescribir谩n si se regenera el c贸digo.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM_DEV.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ASCENSOS
    {
        public int ID_ASCENSO { get; set; }
        public int ID_EMPLEADO { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor, ingrese una Descripci髇"), DisplayName("Descripci髇"), DataType(DataType.MultilineText)]
        public string DESCRIPCION { get; set; }

        [DisplayName("Puesto Anterior")]
        public string PUESTO_ANT { get; set; }

        public int PUESTO_NVO { get; set; }

        [DisplayName("Fecha")]
        public System.DateTime FECHA { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor, ingrese un nombre"), DisplayName("Autorizado por:"), StringLength(30, ErrorMessage = " El nombre del empleado es muy extenso. Por favor no exceda los 30 caracteres."), RegularExpression("([A-Za-z])+( [A-Za-z]+)*", ErrorMessage = "Formato Inv醠ido.")]
        public string AUTORIZACION { get; set; }

        public virtual EMPLEADOS EMPLEADOS { get; set; }
        public virtual PUESTOS PUESTOS { get; set; }

    }
}
