//------------------------------------------------------------------------------
// <auto-generated>
//     Este c贸digo se gener贸 a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicaci贸n.
//     Los cambios manuales en este archivo se sobrescribir谩n si se regenera el c贸digo.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM_DEV.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class EMPLEADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADOS()
        {
            this.AMONESTACIONES = new HashSet<AMONESTACIONES>();
            this.ASCENSOS = new HashSet<ASCENSOS>();
            this.PERMISOS = new HashSet<PERMISOS>();
            this.SUSPENSIONES = new HashSet<SUSPENSIONES>();
            this.VACACIONES = new HashSet<VACACIONES>();
        }

        public int EMP_ID { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor ingrese el N鷐ero de empleado"), DisplayName("N鷐ero de Empleado"), StringLength(9, ErrorMessage = "La longitud de la c閐ula es muy extensa, no exceda los 9 caracteres."), RegularExpression("([1-9][0-9]*)", ErrorMessage = "Formato Inv醠ido (Ingrese n鷐eros.)")]
        public string ID_EMPLEADO { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor ingrese la c閐ula del empleado"), DisplayName("C閐ula"), StringLength(9, ErrorMessage = "La longitud de la c閐ula es muy extensa, no exceda los 9 caracteres."), RegularExpression("([1-9][0-9]*)", ErrorMessage = "Formato Inv醠ido (Ingrese n鷐eros.)")]
        public string CEDULA { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor, ingrese un nombre"), DisplayName("Nombre"), StringLength(30, ErrorMessage = " El nombre del empleado es muy extenso. Por favor no exceda los 30 caracteres."), RegularExpression("([A-Za-z])+( [A-Za-z]+)*", ErrorMessage = "Formato Inv醠ido.")]
        public string NOMBRE { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor, ingrese el primer apellido"), DisplayName("Primer Apellido"), StringLength(15, ErrorMessage = " El apellido del empleado es muy extenso. Por favor no exceda los 15 caracteres."), RegularExpression("([A-Za-z])+( [A-Za-z]+)*", ErrorMessage = "Formato Inv醠ido.")]
        public string APE1 { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor, ingrese el segundo apelliod"), DisplayName("Segundo Apellido"), StringLength(15, ErrorMessage = " El apellido del empleado es muy extenso. Por favor no exceda los 15 caracteres."), RegularExpression("([A-Za-z])+( [A-Za-z]+)*", ErrorMessage = "Formato Inv醠ido.")]
        public string APE2 { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor, ingrese la fecha de nacimiento"), DisplayName("Fecha de Nacimiento"), DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime FECHA_NAC { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor, ingrese la fecha de contrataci髇"), DisplayName("Fecha de Contrataci髇"), DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime FECHA_CONTR { get; set; }

        public int DIAS_VAC_DISP { get; set; }
        public int DIAS_VAC_UTILIZAD { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor, ingrese la direcci髇 del empleado"), DisplayName("Direcci髇"), DataType(DataType.MultilineText)]
        public string DIRECCION { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor, ingrese una Descripci髇"), DisplayName("Descripci髇"), DataType(DataType.MultilineText)]
        public string DESCRIPCION { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor ingrese el tel閒ono de habitaci髇 del empleado"), DisplayName("Tel閒ono de Habitaci髇"), StringLength(8, ErrorMessage = "El n鷐ero es muy extenso, no exceda los 8 caracteres."), RegularExpression("([1-9][0-9]*)", ErrorMessage = "Formato Inv醠ido (Ingrese n鷐eros.)")]
        public string TEL_HABITACION { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor ingrese el tel閒ono m髒il del empleado"), DisplayName("Tel閒ono M髒il"), StringLength(8, ErrorMessage = "El n鷐ero es muy extenso, no exceda los 8 caracteres."), RegularExpression("([1-9][0-9]*)", ErrorMessage = "Formato Inv醠ido (Ingrese n鷐eros.)")]
        public string TEL_MOVIL { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor ingrese un correo electr髇ico v醠ido"), DisplayName("Correo Electr髇ico "), EmailAddress(ErrorMessage = "Correo El閏tronico con formato inv醠ido")]
        public string E_MAIL { get; set; }

        public int PUESTO { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor, ingrese la direcci髇 del empleado"), DisplayName("Salario")]
        public double SALARIO { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor, seleccione el estado del empleado"), DisplayName("Estado")]
        public string ESTADO { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AMONESTACIONES> AMONESTACIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASCENSOS> ASCENSOS { get; set; }
        public virtual PUESTOS PUESTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERMISOS> PERMISOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUSPENSIONES> SUSPENSIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VACACIONES> VACACIONES { get; set; }
    }
}
