//------------------------------------------------------------------------------
// <auto-generated>
//     Este c贸digo se gener贸 a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicaci贸n.
//     Los cambios manuales en este archivo se sobrescribir谩n si se regenera el c贸digo.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM_DEV.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class PUESTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PUESTOS()
        {
            this.ASCENSOS = new HashSet<ASCENSOS>();
            this.EMPLEADOS = new HashSet<EMPLEADOS>();
        }

        public int PTS_ID { get; set; }
        public string ID_PUESTO { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor, ingrese un nombre"), DisplayName("Nombre del Puesto"), StringLength(45, ErrorMessage = " El nombre del puesto es muy extenso. Por favor no exceda los 45 caracteres."), RegularExpression("([A-Za-z])+( [A-Za-z]+)*", ErrorMessage = "Formato Inv醠ido.")]
        public string NOMBRE { get; set; }
        public int DEPARTAMENTO { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor, ingrese el nivel academico requerido para el puesto"), DisplayName("Nivel Acad閙ico"), StringLength(45, ErrorMessage = "Por favor no exceda los 45 caracteres."), RegularExpression("([A-Za-z])+( [A-Za-z]+)*", ErrorMessage = "Formato Inv醠ido.")]
        public string NIVEL_ACADEMICO { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor ingrese la experiencia m韓ima"), DisplayName("Experiencia M韓ima (A駉s)"), StringLength(2, ErrorMessage = "Muchos A駉s."), RegularExpression("([1-9][0-9]*)", ErrorMessage = "Formato Inv醠ido (Ingrese n鷐eros.)")]
        public string EXP_MIN { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor ingrese la experiencia deseada"), DisplayName("Experiencia Deseada (A駉s)"), StringLength(2, ErrorMessage = "Muchos A駉s."), RegularExpression("([1-9][0-9]*)", ErrorMessage = "Formato Inv醠ido (Ingrese n鷐eros.)")]
        public string EXP_DESEADA { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor, ingrese una descripci髇"), DisplayName("Descripci髇 del Puesto"), DataType(DataType.MultilineText)]
        public string DESCRIPCION { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Por favor, seleccione el estado del puesto"), DisplayName("Estado")]
        public string ESTADO { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASCENSOS> ASCENSOS { get; set; }
        public virtual DEPARTAMENTOS DEPARTAMENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADOS> EMPLEADOS { get; set; }
    }
}
