//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM_DEV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public int ID_USUARIO { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string CONTRASEÑA { get; set; }
        public string ESTADO { get; set; }
        public string ACC_EMPRESA { get; set; }
        public string ACC_DEPART { get; set; }
        public string ACC_PUESTOS { get; set; }
        public string ACC_EMPLEADOS { get; set; }
        public string ACC_ACCIONES { get; set; }
        public string ACC_USUARIO { get; set; }
        public string ROL { get; set; }
    }
}
