//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM_DEV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VACACIONES
    {
        public int ID_SOLICITUD { get; set; }
        public int ID_EMPLEADO { get; set; }
        public System.DateTime INICIO { get; set; }
        public System.DateTime FINAL { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public int CANT_DIAS { get; set; }
        public string AUTORIZACION { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual EMPLEADOS EMPLEADOS { get; set; }
    }
}
